"Resource/UI/CSCareerRoundEnd.res"
{
	"CSCareerRoundEnd"
	{
		"ControlName"		"Frame"
		"fieldName"		"CSCareerRoundEnd"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"640"
		"tall"		"480"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"settitlebarvisible"		"0"
	}
	"Wins"
	{
		"ControlName"		"Label"
		"fieldName"		"Wins"
		"xpos"		"70"
		"ypos"		"116"
		"wide"		"200"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"CareerScreen"
	}
	"Losses"
	{
		"ControlName"		"Label"
		"fieldName"		"Losses"
		"xpos"		"70"
		"ypos"		"136"
		"wide"		"200"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"CareerScreen"
	}
	"Needed"
	{
		"ControlName"		"Label"
		"fieldName"		"Needed"
		"xpos"		"70"
		"ypos"		"193"
		"wide"		"500"
		"tall"		"40"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"CareerScreen"
		"wrap"			"1"
	}
	"RoundResult"
	{
		"ControlName"		"Label"
		"fieldName"		"RoundResult"
		"xpos"		"70"
		"ypos"		"22"
		"wide"		"500"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Career_RoundWin"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"Title"
	}
	"Task0"
	{
		"ControlName"		"TaskLabel"
		"fieldName"		"Task0"
		"xpos"		"70"
		"ypos"		"260"
		"wide"		"450"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"Task"
	}
	"TaskStatus0"
	{
		"ControlName"		"TaskLabel"
		"fieldName"		"TaskStatus0"
		"xpos"		"520"
		"ypos"		"260"
		"wide"		"100"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"Task"
	}
	"Task1"
	{
		"ControlName"		"TaskLabel"
		"fieldName"		"Task1"
		"xpos"		"70"
		"ypos"		"276"
		"wide"		"450"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"Task"
	}
	"TaskStatus1"
	{
		"ControlName"		"TaskLabel"
		"fieldName"		"TaskStatus1"
		"xpos"		"520"
		"ypos"		"276"
		"wide"		"100"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"Task"
	}
	"Task2"
	{
		"ControlName"		"TaskLabel"
		"fieldName"		"Task2"
		"xpos"		"70"
		"ypos"		"292"
		"wide"		"450"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"Task"
	}
	"TaskStatus2"
	{
		"ControlName"		"TaskLabel"
		"fieldName"		"TaskStatus2"
		"xpos"		"520"
		"ypos"		"292"
		"wide"		"100"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"Task"
	}
	"Task3"
	{
		"ControlName"		"TaskLabel"
		"fieldName"		"Task3"
		"xpos"		"70"
		"ypos"		"308"
		"wide"		"450"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"Task"
	}
	"TaskStatus3"
	{
		"ControlName"		"TaskLabel"
		"fieldName"		"TaskStatus3"
		"xpos"		"520"
		"ypos"		"308"
		"wide"		"100"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"Task"
	}
	"Task4"
	{
		"ControlName"		"TaskLabel"
		"fieldName"		"Task4"
		"xpos"		"70"
		"ypos"		"324"
		"wide"		"450"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"Task"
	}
	"TaskStatus4"
	{
		"ControlName"		"TaskLabel"
		"fieldName"		"TaskStatus4"
		"xpos"		"520"
		"ypos"		"324"
		"wide"		"100"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"Task"
	}
	"Task5"
	{
		"ControlName"		"TaskLabel"
		"fieldName"		"Task5"
		"xpos"		"70"
		"ypos"		"340"
		"wide"		"450"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"Task"
	}
	"TaskStatus5"
	{
		"ControlName"		"TaskLabel"
		"fieldName"		"TaskStatus5"
		"xpos"		"520"
		"ypos"		"340"
		"wide"		"100"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"Task"
	}
	"Task6"
	{
		"ControlName"		"TaskLabel"
		"fieldName"		"Task6"
		"xpos"		"70"
		"ypos"		"356"
		"wide"		"450"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"Task"
	}
	"TaskStatus6"
	{
		"ControlName"		"TaskLabel"
		"fieldName"		"TaskStatus6"
		"xpos"		"520"
		"ypos"		"356"
		"wide"		"100"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"Task"
	}
	"Task7"
	{
		"ControlName"		"TaskLabel"
		"fieldName"		"Task7"
		"xpos"		"70"
		"ypos"		"372"
		"wide"		"450"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"Task"
	}
	"TaskStatus7"
	{
		"ControlName"		"TaskLabel"
		"fieldName"		"TaskStatus7"
		"xpos"		"520"
		"ypos"		"372"
		"wide"		"100"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"Task"
	}
	"ImminentVictory"
	{
		"ControlName"		"Label"
		"fieldName"		"ImminentVictory"
		"xpos"		"70"
		"ypos"		"388"
		"wide"		"400"
		"tall"		"32"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"MapComplete"
		"wrap"			"1"
	}
	"TaskNotice"
	{
		"ControlName"		"Label"
		"fieldName"		"TaskNotice"
		"xpos"		"70"
		"ypos"		"236"
		"wide"		"400"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		""
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"CareerScreen"
	}
	"TopLeftPanel"
	{
		"ControlName"		"Panel"
		"fieldName"		"TopLeftPanel"
		"xpos"		"20"
		"ypos"		"20"
		"wide"		"10"
		"tall"		"10"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"TopRightPanel"
	{
		"ControlName"		"Panel"
		"fieldName"		"TopRightPanel"
		"xpos"		"610"
		"ypos"		"20"
		"wide"		"10"
		"tall"		"10"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"BottomLeftPanel"
	{
		"ControlName"		"Panel"
		"fieldName"		"BottomLeftPanel"
		"xpos"		"20"
		"ypos"		"450"
		"wide"		"10"
		"tall"		"10"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"BottomRightPanel"
	{
		"ControlName"		"Panel"
		"fieldName"		"BottomRightPanel"
		"xpos"		"610"
		"ypos"		"450"
		"wide"		"10"
		"tall"		"10"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"GapPanel"
	{
		"ControlName"		"Panel"
		"fieldName"		"GapPanel"
		"xpos"		"20"
		"ypos"		"72"
		"wide"		"600"
		"tall"		"2"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"ScoreSoFar"
	{
		"ControlName"		"Label"
		"fieldName"		"ScoreSoFar"
		"xpos"		"70"
		"ypos"		"86"
		"wide"		"200"
		"tall"		"20"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Career_ScoreSoFar"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"font"			"CareerScreen"
	}
	"ok"
	{
		"ControlName"		"Button"
		"fieldName"		"ok"
		"xpos"		"480"
		"ypos"		"425"
		"wide"		"127"
		"tall"		"19"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Career_ContinueMatch"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"career_continue"
		"Default"		"1"
		"font"			"CareerScreen"
	}
	"surrender"
	{
		"ControlName"		"Button"
		"fieldName"		"surrender"
		"xpos"		"343"
		"ypos"		"425"
		"wide"		"127"
		"tall"		"19"
		"autoResize"		"0"
		"pinCorner"		"2"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Career_Surrender"
		"textAlignment"		"center"
		"dulltext"		"0"
		"brighttext"		"0"
		"Command"		"disconnect"
		"Default"		"0"
		"font"			"CareerScreen"
	}
	"Divider1"
	{
		"ControlName"		"Divider"
		"fieldName"		"Divider1"
		"xpos"		"70"
		"ypos"		"176"
		"wide"		"500"
		"tall"		"2"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"ExclamationPanel"
	{
		"ControlName"		"Panel"
		"fieldName"		"ExclamationPanel"
		"xpos"		"26"
		"ypos"		"26"
		"wide"		"40"
		"tall"		"40"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
}
 